language: cpp
compiler:
    - g++
before_install:
    - sudo apt-get update -qq
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.8; fi
    - sudo apt-get install -qq libboost-system-dev libboost-filesystem-dev
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
