language: cpp

cache:
    directories:
        - foam-extend-3.1

compiler:
    - g++

before_install:
    - sudo apt-get update -qq
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8 rpm libboost-system-dev cmake git git-core flex bison libboost-filesystem-dev cmake libopenmpi-dev openmpi-bin openmpi-common openmpi-checkpoint
    - sudo apt-get install -qq metis-edf libmetis-edf-dev
    - sudo apt-get install -qq libparmetis-dev
    - sudo apt-get install -qq scotch libscotch-dev
    - sudo apt-get install -qq hwloc libhwloc-dev
    - sudo apt-get install -qq build-essential binutils-dev zlib1g-dev qt4-dev-tools libqt4-dev libncurses5-dev libxt-dev mercurial graphviz
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - gcc --version

before_script:
    - if [ ! -d "foam-extend-3.1" ]; then git clone --branch nextRelease git://git.code.sf.net/p/openfoam-extend/foam-extend-3.1; fi
    - pwd
    - echo $HOME
