language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - build-essential
            - flex
            - bison
            - zlib1g-dev
            - libreadline-dev
            - libncurses5-dev
            - libxt-dev
            - libopenmpi-dev
            - openmpi-bin
            - rpm
            - wget
            - hwloc
            - scotch
            - gfortran
            - python
            - unzip
            - scons
            - binutils-dev
            - petsc-dev
            - libdeal.ii-dev

before_install:
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"
    - export OMPI_CXX=$CXX
    - export OMPI_CC=$CC

cache:
    directories:
        - foam-extend-3.2
        - src/thirdParty/yaml-cpp-release-0.5.3
        - src/thirdParty/gtest-1.7.0
        - src/thirdParty/boost_1_55_0

script:
    - if [ ! -d "foam-extend-3.2/.git" ]; then rm -rf foam-extend-3.2 && git clone --branch v3.2 git://git.code.sf.net/p/openfoam-extend/foam-extend-3.1 foam-extend-3.2; fi
    - export PARAVIEW_SYSTEM=1
    - export HWLOC_SYSTEM=1
    - export SCOTCH_SYSTEM=1
    - export PYFOAM_SYSTEM=1
    - export CUDA_IGNORE=1
    - export SWAK4FOAM_SYSTEM=1
    - export WM_MPLIB=SYSTEMOPENMPI
    - export OPENMPI_DIR=/usr
    - export OPENMPI_BIN_DIR=$OPENMPI_DIR/bin
    - export FOAM_INST_DIR=`pwd`
    - sed -i s/"CC          = g++ -m64"/"CC          = mpicxx -m64"/g foam-extend-3.2/wmake/rules/linux64Gcc/c++
    - cd foam-extend-3.2
    - source etc/bashrc
    - export WM_NCOMPPROCS=1
    - unset WM_THIRD_PARTY_USE_HWLOC_1101
    - unset WM_THIRD_PARTY_USE_SCOTCH_604
    - unset WM_THIRD_PARTY_USE_PYFOAM_064
    - ( cd wmake/src && make )
    - ( cd $WM_THIRD_PARTY_DIR && ./AllMake )
    - . $WM_PROJECT_DIR/etc/settings.sh
    - cd $WM_PROJECT_DIR/src
    - wmakePrintBuild -check || /bin/rm -f foam/Make/$WM_OPTIONS/global.? 2>/dev/null
    - wmakeLnInclude foam
    - wmakeLnInclude meshTools
    - wmakeLnInclude OSspecific/$WM_OSTYPE
    - wmake libo  OSspecific/$WM_OSTYPE
    - wmake libso foam
    - decompositionMethods/AllwmakeLnInclude
    # - decompositionMethods/Allwmake
    - wmake libso lagrangian/basic
    - wmake libso edgeMesh
    - wmake libso surfMesh
    - wmake libso meshTools
    - wmake libso finiteVolume
    - wmake libso finiteArea
    - wmake libso lduSolvers
    - wmake libso tetFiniteElement
    - dynamicMesh/AllwmakeLnInclude
    - dynamicMesh/Allwmake
    - wmake libso coupledMatrix
    - wmake libso sampling
    - wmake libso ODE
    - mesh/Allwmake
    - thermophysicalModels/Allwmake
    - transportModels/Allwmake
    - turbulenceModels/Allwmake
    - lagrangian/Allwmake
    - postProcessing/Allwmake
    - conversion/Allwmake
    # - export FOAM_USER_SRC=`pwd`/src
    # - ./Allwmake.firstInstall

    - cd $FOAM_INST_DIR/src/thirdParty
    - if [ ! -e "gtest-1.7.0/libgtest.a" ]; then rm -rf gtest*; echo "remove gtest"; fi
    - if [ ! -e "boost_1_55_0/bootstrap.sh" ]; then rm -rf boost*; echo "remove boost"; fi
    - if [ ! -e "yaml-cpp-release-0.5.3/build/libyaml-cpp.so.0.5.3" ]; then rm -rf yaml-cpp*; echo "remove yaml-cpp"; fi

    - ./compile_gtest
    - ./compile_yaml
