language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - build-essential
            - flex
            - bison
            - zlib1g-dev
            - libreadline-dev
            - libncurses5-dev
            - libxt-dev
            - libopenmpi-dev
            - openmpi-bin
            - rpm
            - wget
            - cmake
            - hwloc
            - scotch
            - gfortran
            - python
            - unzip
            - scons
            - binutils-dev

before_install:
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"
    - export OMPI_CXX=$CXX
    - export OMPI_CC=$CC

cache:
    directories:
        - foam-extend-3.2
        # - src/thirdParty/gtest-1.7.0
        # - src/thirdParty/metis-5.1.0
        # - src/thirdParty/parmetis-4.0.3
        # - src/thirdParty/petsc-3.6.3
        # - src/thirdParty/yaml-cpp-release-0.5.3
        # - src/thirdParty/boost_1_55_0

script:
    - if [ ! -d "foam-extend-3.2/.git" ]; then rm -rf foam-extend-3.2 && git clone --branch v3.2 git://git.code.sf.net/p/openfoam-extend/foam-extend-3.1 foam-extend-3.2; fi
    - export PARAVIEW_SYSTEM=1
    - export CMAKE_SYSTEM=1
    - export HWLOC_SYSTEM=1
    - export SCOTCH_SYSTEM=1
    - export PYFOAM_SYSTEM=1
    - export CUDA_IGNORE=1
    - export SWAK4FOAM_SYSTEM=1
    - export WM_MPLIB=SYSTEMOPENMPI
    - export OPENMPI_DIR=/usr
    - export OPENMPI_BIN_DIR=$OPENMPI_DIR/bin
    - export FOAM_INST_DIR=`pwd`
    - sed -i s/"CC          = g++ -m64"/"CC          = mpicxx -m64"/g foam-extend-3.2/wmake/rules/linux64Gcc/c++
    - cd foam-extend-3.2
    - source etc/bashrc
    - export WM_NCOMPPROCS=2
    - unset WM_THIRD_PARTY_USE_CMAKE_322
    - unset WM_THIRD_PARTY_USE_HWLOC_1101
    - unset WM_THIRD_PARTY_USE_SCOTCH_604
    - unset WM_THIRD_PARTY_USE_PYFOAM_064
    - ( cd wmake/src && make )
    - ( cd $WM_THIRD_PARTY_DIR && ./AllMake )
    - cd $WM_PROJECT_DIR/src
    - wmakePrintBuild -check || /bin/rm -f foam/Make/$WM_OPTIONS/global.? 2>/dev/null
    - wmakeLnInclude foam
    - wmake libso lagrangian/basic
    - wmake libso edgeMesh
    - wmake libso surfMesh
    - wmakeLnInclude meshTools
    - wmakeLnInclude OSspecific/$WM_OSTYPE
    - wmake libo  OSspecific/$WM_OSTYPE
    - wmake libso foam
    - wmake libso meshTools
    - wmake libso finiteVolume
    - wmake libso finiteArea
    - dynamicMesh/AllwmakeLnInclude
    - dynamicMesh/Allwmake
    - wmake libso coupledMatrix
    # - decompositionMethods/AllwmakeLnInclude
    # - decompositionMethods/Allwmake
    # - cd ..
    # - export FOAM_USER_SRC=`pwd`/src
    # - ./Allwmake.firstInstall

    # - cd $FOAM_INST_DIR/src/thirdParty
    # - if [ ! -d "gtest-1.7.0/libgtest.a" ]; then rm -rf gtest*; fi
    # - if [ ! -d "metis-5.1.0/build/lib/libmetis.a" ]; then rm -rf metis*; fi
    # - if [ ! -d "parmetis-4.0.3/build/lib/libparmetis.a" ]; then rm -rf parmetis*; fi
    # - if [ ! -d "petsc-3.6.3/x86_64/lib/libpetsc.so.3.6.3" ]; then rm -rf petsc*; fi
    # - if [ ! -d "dealii-8.3.0/bin/lib/libdeal_II.so" ]; then rm -rf dealii*; fi
    # - if [ ! -d "boost_1_55_0/bootstrap.sh" ]; then rm -rf boost*; fi
    # - ./compile_precice
    # - ./compile_gtest
    # - ./compile_yaml
